### PR TITLE
Add MGG-BUSD farm, add MGG token

### LINKED ISSUE #79: Add new pools / farms [ MGG - BUSD ]
STAKING INFO 
* LP Address / Staking Token: [0xb2F6FE5e9C83ad968fde18306D35caf8555BcD9f](https://bscscan.com/address/0xb2f6fe5e9c83ad968fde18306d35caf8555bcd9f)
* Staking Address: [0xaE712e16960B85F1624a7242f9F66CE752c4b774](https://bscscan.com/address/0xae712e16960b85f1624a7242f9f66ce752c4b774)

### PR DESCRIPTION
**Pull request by kojiadrianojr**
closes #79 

TOKEN INFO:
```
  mgg: {
    symbol: 'MGG',
    address: {
      97: '',
      56: '0x6125aDCAb2F171BC70cfe2CAeCFeC5509273A86A'
    },
    decimals: 18,
    projectLink: 'https://www.metagg.com/'
  },
```

FARM INFO:
```
 {
    pid: 264,
    lpSymbol: 'MGG-BUSD LP',
    lpAddresses: {
      97: '',
      56: '0xb2F6FE5e9C83ad968fde18306D35caf8555BcD9f',
    },
    stakingAddresses: {
      97: '',
      56: '0xaE712e16960B85F1624a7242f9F66CE752c4b774',
    },
    token: tokens.mgg,
    pairToken: tokens.busd,
    quoteToken: tokens.mgg,
    isPromoted: 1
  },
```

### CODE REVIEW

**Comment by mativanarquero** [comment]
Su icon pala semi-master @kojiadrianojr ng mgg?

**Review by mativanarquero — APPROVED** [review]
LGTM!

**Comment by kojiadrianojr** [comment]
Okay na @mativanarquero

**Comment by mativanarquero** [comment]
Need to lint semi-master @kojiadrianojr

**Comment by kojiadrianojr** [comment]
Okay na, updated.

**Comment by mativanarquero** [comment]
Updated MGG-BUSD LP staking address from '_0xaE712e16960B85F1624a7242f9F66CE752c4b774_' to '_0x57DE775D524545Fab61978b60312ada906CFE355_'

**Review by aldrickb — APPROVED** [review]

**Pull request merged**
