### PR TITLE
style: Update farm cards and deposit modal

### PR DESCRIPTION
**Pull request by mativanarquero**
- [x] Remove 's' - total deposits: - farmcard
- [x] Change 'Unlock Wallet' to 'Connect Wallet' - UnlockButton component
- [x] Remove colons - Titles - Farm cards
- [x] Capitalize 'Earn' - Card Heading
- [x] Update 'Claim and withdraw' to 'Claim & Withdraw - Button text

farm_card_ui
deposit_modal

### CODE REVIEW

**Comment by kojiadrianojr** [comment]
NOTE: Wala yang image kasi naka testnet ka @mativanarquero 
amarayt?

**Comment by mativanarquero** [comment]
> NOTE: Wala yang image kasi naka testnet ka @mativanarquero
> amarayt?

Yezzir naka test net po ako

**Review by swengr-janan — APPROVED** [review]
Enhanced!

**Comment by kojiadrianojr** [comment]
Copy @mativanarquero

**Pull request merged**
