### PR TITLE
[SPSTK-14] [SPSTK-15] Replace and convert remaining blocks to remaining days and make pool links distinctive 

### PR DESCRIPTION
**Pull request by mativanarquero**
p_c

### CODE REVIEW

**Review by swengr-janan — APPROVED** [review]
AGITH!

**Comment by kojiadrianojr** [comment]
Inalis mo na yung blocks?

**Comment by kojiadrianojr** [comment]
What if mag add ka @mativanarquero ivan ng small button na pwede pagpalitin yung blocks or days gusto moa view ni user? kabit mo lang sa 'remaining days' ?

**Comment by kojiadrianojr** [comment]
also nevermind pala, for future nalang since ililipat naman natin yan pala

**Comment by mativanarquero** [comment]
> Inalis mo na yung blocks?

Anjan parin semi-master @kojiadrianojr, cinomment out ko lang muna since 'replace' yung naka tag sa improvements

**Comment by mativanarquero** [comment]
> also nevermind pala, for future nalang since ililipat naman natin yan pala

Okay copy copy noted ito paps @kojiadrianojr thank you

**Pull request merged**
