### PR TITLE
Add Pools filter and Merge Farms Banner 

### PR DESCRIPTION
**Pull request by mativanarquero**
Pools
- Add Switch Tab/ filter and search component
pools_up
- Fix Upcoming tab rendering
upcoming_render 

Farms
- Redirect nav bar 'Farms' to '/farms'
- Merge farms banner from `add-banner-farms`
farms_ui

### CODE REVIEW

**Review by harveyjavier — APPROVED** [review]
Organized

**Review by kbaldo — APPROVED** [review]
Filtered and merged! 🌿

**Review by swengr-janan — APPROVED** [review]
Retrica Lordszx!

**Comment by harveyjavier** [comment]
> Retrica Lordszx!

Hanep na Retrica haha classic!

**Pull request merged**
