### PR TITLE
Update staking modal links

### PR DESCRIPTION
**Pull request by mativanarquero**
- [x] Resolves: Properly align image same with Pools #20
- [x] Resolves: Add _blank when redirecting to a link #18

Redirect Add More and Add Liquidity links to open in new tab
farms_redirect

Align header image
farms_header_image

### CODE REVIEW

**Review by swengr-janan — APPROVED** [review]
Up to date!

**Review by kbaldo — APPROVED** [review]
Resolved!

**Review by harveyjavier — APPROVED** [review]
Linked!

**Review by Pseudoman21 — APPROVED** [review]
Redirected!

**Pull request merged**
