### PR TITLE
Resolve WC connector issues

### LINKED ISSUE #91: Never ending animation icon and no popup to notify the user regarding a successful stake
https://user-images.githubusercontent.com/61826995/165433019-8570782a-a7fa-446c-b8a6-558f92384f21.mp4

https://user-images.githubusercontent.com/61826995/165433027-33493b9e-39c2-4234-bef7-cafba846e022.mp4

### PR DESCRIPTION
**Pull request by kojiadrianojr**
closes #91

### CODE REVIEW

**Comment by kojiadrianojr** [comment]
pa test neton @swengr-janan kahit metamask -> wallet connect using scan baga

**Comment by swengr-janan** [comment]
di man sya ma test sa desktop ta iba man wallet connect sa desktop, unlike sa mobile may list

**Comment by swengr-janan** [comment]
https://docs.google.com/document/d/1XosmYWhC0JLBHByu5d3EpsOoECT3rPY4MrnWqGCwt5g/edit

**Review by mativanarquero — APPROVED** [review]
LGTM

**Comment by kojiadrianojr** [comment]
@swengr-janan kaya siya metamask pero QR kaso :<

**Review by swengr-janan — CHANGES_REQUESTED** [review]
patanggal console log tol
Screen Shot 2022-04-29 at 1 16 28 PM

**Review by swengr-janan — APPROVED** [review]

**Pull request merged**
